/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Signup = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addSignup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Signup = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addSignup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getSignupCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };